model_types = ["MLTU", "wav2vec2", "whisper"]
models_dir = "Models/"
autocorrect_languages = {"Polish": "pl",
                         "English": "en",
                         "Ukrainian": "uk",
                         "Turkish": "tr",
                         "Spanish": "es",
                         "French": "fr"}
languages = {'Afar': 'aa', 'Abkhazian': 'ab', 'Avestan': 'ae', 'Afrikaans': 'af', 'Akan': 'ak',
             'Amharic': 'am', 'Aragonese': 'an', 'Arabic': 'ar', 'Assamese': 'as', 'Avaric': 'av',
             'Aymara': 'ay', 'Azerbaijani': 'az', 'Bashkir': 'ba', 'Belarusian': 'be', 'Bulgarian': 'bg',
             'Bihari languages': 'bh', 'Bislama': 'bi', 'Bambara': 'bm', 'Bangla': 'bn', 'Tibetan': 'bo',
             'Breton': 'br', 'Bosnian': 'bs', 'Catalan': 'ca', 'Chechen': 'ce', 'Chamorro': 'ch',
             'Corsican': 'co', 'Cree': 'cr', 'Czech': 'cs', 'Church Slavic': 'cu', 'Chuvash': 'cv',
             'Welsh': 'cy', 'Danish': 'da', 'German': 'de', 'Divehi': 'dv', 'Dzongkha': 'dz', 'Ewe': 'ee',
             'Greek': 'el', 'English': 'en', 'Esperanto': 'eo', 'Spanish': 'es', 'Estonian': 'et',
             'Basque': 'eu', 'Persian': 'fa', 'Fulah': 'ff', 'Finnish': 'fi', 'Fijian': 'fj',
             'Faroese': 'fo', 'French': 'fr', 'Western Frisian': 'fy', 'Irish': 'ga',
             'Scottish Gaelic': 'gd', 'Galician': 'gl', 'Guarani': 'gn', 'Gujarati': 'gu', 'Manx': 'gv',
             'Hausa': 'ha', 'Hebrew': 'iw', 'Hindi': 'hi', 'Hiri Motu': 'ho', 'Croatian': 'hr',
             'Haitian Creole': 'ht', 'Hungarian': 'hu', 'Armenian': 'hy', 'Herero': 'hz',
             'Interlingua': 'ia', 'Indonesian': 'in', 'Interlingue': 'ie', 'Igbo': 'ig',
             'Sichuan Yi': 'ii', 'Inupiaq': 'ik', 'Ido': 'io', 'Icelandic': 'is', 'Italian': 'it',
             'Inuktitut': 'iu', 'Japanese': 'ja', 'Javanese (jv)': 'jv', 'Javanese (jw)': 'jw',
             'Georgian': 'ka', 'Kongo': 'kg', 'Kikuyu': 'ki', 'Kuanyama': 'kj', 'Kazakh': 'kk',
             'Kalaallisut': 'kl', 'Khmer': 'km', 'Kannada': 'kn', 'Korean': 'ko', 'Kanuri': 'kr',
             'Kashmiri': 'ks', 'Kurdish': 'ku', 'Komi': 'kv', 'Cornish': 'kw', 'Kyrgyz': 'ky',
             'Latin': 'la', 'Luxembourgish': 'lb', 'Ganda': 'lg', 'Limburgish': 'li', 'Lingala': 'ln',
             'Lao': 'lo', 'Lithuanian': 'lt', 'Luba-Katanga': 'lu', 'Latvian': 'lv', 'Malagasy': 'mg',
             'Marshallese': 'mh', 'Māori': 'mi', 'Macedonian': 'mk', 'Malayalam': 'ml', 'Mongolian': 'mn',
             'Marathi': 'mr', 'Malay': 'ms', 'Maltese': 'mt', 'Burmese': 'my', 'Nauru': 'na',
             'Norwegian Bokmål': 'nb', 'Nepali': 'ne', 'Ndonga': 'ng', 'Dutch': 'nl', 'Norwegian Nynorsk': 'nn',
             'Norwegian': 'no', 'South Ndebele': 'nr', 'Navajo': 'nv', 'Nyanja': 'ny', 'Occitan': 'oc', 'Oromo': 'om',
             'Odia': 'or', 'Ossetic': 'os', 'Punjabi': 'pa', 'Polish': 'pl', 'Pashto': 'ps', 'Portuguese': 'pt',
             'Quechua': 'qu', 'Romansh': 'rm', 'Rundi': 'rn', 'Romanian': 'ro', 'Russian': 'ru', 'Kinyarwanda': 'rw',
             'Sanskrit': 'sa', 'Sardinian': 'sc', 'Sindhi': 'sd', 'Northern Sami': 'se', 'Sango': 'sg',
             'Serbian (Latin)': 'sh', 'Sinhala': 'si', 'Slovak': 'sk', 'Slovenian': 'sl', 'Samoan': 'sm',
             'Shona': 'sn', 'Somali': 'so', 'Albanian': 'sq', 'Serbian': 'sr', 'Swati': 'ss', 'Southern Sotho': 'st',
             'Sundanese': 'su', 'Swedish': 'sv', 'Swahili': 'sw', 'Tamil': 'ta', 'Telugu': 'te', 'Tajik': 'tg',
             'Thai': 'th', 'Tigrinya': 'ti', 'Turkmen': 'tk', 'Filipino': 'tl', 'Tswana': 'tn', 'Tongan': 'to',
             'Turkish': 'tr', 'Tsonga': 'ts', 'Tatar': 'tt', 'Twi': 'tw', 'Tahitian': 'ty', 'Uyghur': 'ug',
             'Ukrainian': 'uk', 'Urdu': 'ur', 'Uzbek': 'uz', 'Venda': 've', 'Vietnamese': 'vi', 'Volapük': 'vo',
             'Walloon': 'wa', 'Wolof': 'wo', 'Xhosa': 'xh', 'Yiddish': 'yi', 'Yoruba': 'yo', 'Zhuang': 'za',
             'Chinese': 'zh', 'Zulu': 'zu'}
